// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "|;-y-Z4vE`]{m1m7QmkO":
            case "Skully":return img`
........................
........................
........................
........................
..........3333..........
........33111133........
.......3b111111b3.......
.......3d11111113.......
......3dd1111111d3......
......3ddd111111d3......
......3dddddd111d3......
......3bddddbcd1d3......
......3cbbbdccddb3......
.......3cbb111113.......
........333331b13.......
........3b111c3b3.......
........33b1b133........
......3.333b3b3.........
......33333333..........
.......33333............
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
